[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crowdsale = "RWRusdKFaiDdu8ht7bTkWmh8uJtPSEAuMYUxKuKd1gU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/letri/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
